# Generated by Django 4.2.4 on 2023-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logisticssite', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decs',
            field=models.CharField(default='This is a default description.', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='my-slug'),
        ),
    ]
