# Generated by Django 4.2.4 on 2023-09-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logisticssite', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
