# Generated by Django 4.2.4 on 2023-10-10 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('delivery_instructions', models.TextField()),
                ('estimated_time', models.CharField(max_length=100)),
                ('total_cost', models.CharField(max_length=50)),
                ('items', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('PU', 'picked up'), ('D', 'delivered'), ('C', 'cancelled')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-date'],
            },
        ),
    ]
