# Generated by Django 4.2.4 on 2023-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('PU', 'picked up'), ('D', 'delivered'), ('C', 'cancelled')], default='P', max_length=2),
        ),
    ]
